name: Create archive and release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}    
    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        type: 'tar'
        directory: 'T2'
        filename: '/build/T2.tar.gz'
        exclusions: '*.git*'
    - name : Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        artifacts: "/build/T2.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}