name: Create Archive
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'tar'
        directory: 'T2'
        filename: '/tmp/T2.tar.gz'
        exclusions: '*.git*'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/tmp/T2.tar.gz"
        tag : "release"
        token: ${{ secrets.GITHUB_TOKEN }}